### ISSUE TITLE
Templated Registry Submissions

### ISSUE THREAD

**Issue by TimothyTickle** [HumanCellAtlas/data-portal-content#101]
# Why
As a methodologist or artist, I would like to be able to submit a visualization or methodology to be listed in the methods registry

# Definition of Done
 - When the "submit your package" link on https://dev.data.humancellatlas.org/analyze/methods/about is clicked a templated submission is started for a methology submission.
- When the "submit your package" link on https://dev.data.humancellatlas.org/analyze/visualization-components/about is clicked a templated submission is started for a visualization submission.

**Comment by jodihir** [comment]
Notes on this request for @NoopDog:
Users will submit details on their method or visualization entries, so we need templates into wich they can add those details.  Template should come up with they click on "submit your package".
Once they've entered everything, can we add a link to the details below the "view" button on this page: https://dev.data.humancellatlas.org/analyze/visualization-components/visualization-components?

**Comment by theathorn** [comment]
@NoopDog to reach out to @TimothyTickle to refine the requirements.

**Comment by jodihir** [comment]
@NoopDog will reach out to @eweitz about this ticket this week as time permits (Tim and Vicky are out of town.)

**Comment by jodihir** [comment]
@NoopDog, Tim is back so please reach out to him to finish up this ticket.

**Comment by jodihir** [comment]
@NoopDog will schedule a call with @TimothyTickle and @eweitz to discuss requirements and how to move forward

**Comment by jodihir** [comment]
@NoopDog were you able to schedule a call with Tim?  They are ready any time you are to work on this.

**Comment by eweitz** [comment]
I'll need a way to provide a URL that comprises the href value in a button link.  

One button would be for methods and appear at left in: https://dev.data.humancellatlas.org/analyze/methods/methods.

One button would be for visualization components and appear at left in: https://dev.data.humancellatlas.org/analyze/visualization-components/visualization-components/.

**Comment by NoopDog** [comment]
@eweitz can you update this ticket please with the pull request template you are looking for? Maybe add it to the definition of done above.  Thanks!

**Comment by NoopDog** [comment]
Hi @eweitz pinging on the content of the template. Cheers, D

**Comment by vickylihorst** [comment]
Hi @NoopDog, thanks for the reminder. We were planning on working on the content of the template starting next sprint (11/1), thinking your schedule would be less crazy given the HCA release. 

Does working on providing the content starting 11/1 work for you?

**Comment by eweitz** [comment]
@NoopDog, @jlchang, and any others interested in this: please see content in the proposed issue templates in https://github.com/HumanCellAtlas/data-portal-content/pull/192/files.

**Comment by eweitz** [comment]
This is done.  See "submit your..." links in:

* https://dev.data.humancellatlas.org/analyze/portals/about
* https://dev.data.humancellatlas.org/analyze/methods/about
* https://dev.data.humancellatlas.org/analyze/visualization-components/about
