### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-portal-content#106]
# Why
Content writers can easily access the style guidelines.

# Definition of Done
Add this style guide: https://docs.google.com/document/d/1xzUXnozewMhmePqYmFzfFpwoI-UdZd6ds3EFx1Cq7EQ/edit
 to the Content Guide section: https://dev.data.humancellatlas.org/document/creating-content/editing-an-existing-page/

**Comment by jodihir** [comment]
Do this by linking to the READMe in the Data Portal Content repo: https://github.com/HumanCellAtlas/data-portal-content/

**Comment by NoopDog** [comment]
@jodihir let me know when this is ready to include in the content guide. Thx

**Comment by jodihir** [comment]
I think we can add this now; if you create the stub doc I can add the parts that are clear (most of the doc) and add the rest later when decisions are made.

**Comment by NoopDog** [comment]
@frano-m can you pease add a doc called content-style-guide.md herehttps://github.com/HumanCellAtlas/data-portal-content/tree/master/content/document/creating-content

Also make this a 2nd level heading under "Content Guide"

So the top bar will be "Creating Content" then "Style Guide"

**Comment by jodihir** [comment]
I'm putting this in the Done column; it's a dynamic internal doc that we can correct and update as we make new style decisions.

**Comment by NoopDog** [comment]
@jodihir this is live here https://dev.data.humancellatlas.org/document/creating-content/content-style-guide

Thx
D
