### ISSUE TITLE
Consumer CLI - download a manifest of files

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-portal-content#11]
# Why
As a user I would like be able to use the manifest file created from the data browser to download all the files in the manifest 

# Definition of Done
 - [ ] describe how to use the manifest download command. Describe the results.

**Comment by theathorn** [comment]
After downloading manifest in Data Browser user is presented with a "Get Download Instructions" button which redirects to https://dev.data.humancellatlas.org/learn/userguides/accessing-data/using-the-cli-to-access-data/. This content needs updating.

**Comment by kozbo** [comment]
This menu item no longer exists, so closing ticket. Now covered by #53
