### ISSUE TITLE
Vertical scrollbar in the tabs of the about page

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/data-portal-content#110]
# Details

## Expected
The tabs in the about page should be flat/fixed.

## Actual
A small scrollbar appears that allows users to scroll through the tab frame/section vertically.

## Setup

This problem exists on both these configurations:
- [Firefox 61 on macOS 10.13](https://whatsmybrowser.org/b/K2UDRK8)
![Firefox 61](https://images.zenhubusercontent.com/5b042c804b5806bc2bd426f0/1b0b9d9d-7a16-4c86-ba5c-d8a829d2e2d9)
- [Safari 11 on macOS 10.13](https://whatsmybrowser.org/b/PU8SGQ9)
![Safari 11](https://images.zenhubusercontent.com/5b042c804b5806bc2bd426f0/6a40591b-7c70-4e0a-9509-0fdcdb458aa1)

# Definition of Done
- [ ] Scroll bar is fixed in Firefox 61
- [ ] Scroll bar is fixed in Safari 11

**Comment by NoopDog** [comment]
Thanks!

**Comment by frano-m** [comment]
@NoopDog I noticed this yesterday and the fix should be in that last PR

**Comment by frano-m** [comment]
@NoopDog I'll need to confirm if solution fixed for firefox

**Comment by NoopDog** [comment]
@rdgoite Hi Rodney, is this looking fixed for you now?

**Comment by rdgoite** [comment]
I can confirm that this issue is now fixed for both Firefox 61 and Safari 11.
