### ISSUE TITLE
update all instances of Secondary Analysis (or Secondary Analysis Service) to Data Processing Pipelines, and Tertiary Analysis to Analysis Applications

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#113]
# Why
We want to remove the notion of primary, secondary, tertiary in terms of analysis, and not imply that these are required steps in processing of any data or data type. 

# Definition of Done
all instances of "secondary" and "tertiary" in content on the portal and in links is updated. "Secondary Analysis" is updated to "Data processing pipelines" and "tertiary analysis" is updated to "analysis applications

Spreadsheet of pages and menu links needing wording updates is here: https://docs.google.com/spreadsheets/d/1zqjJ_qOIIi4QfTE3kbd2tJuvCiLEtgF4WSj-Tn-oePg/edit#gid=0

@NoopDog I only noticed these 2 pages that need updates in the left-hand or top menus:
https://dev.data.humancellatlas.org/about/what-is-the-platform/what-is-the-platform
https://dev.data.humancellatlas.org/develop/development-guides/development-guides-overview

**Comment by kozbo** [comment]
Keep looking this week, will close Sept 7 if no more are found

**Comment by jodihir** [comment]
@NoopDog 
1. The About section re-write of the secondary analysis page is in master now, so please change the Secondary Analysis menu item (https://dev.data.humancellatlas.org/about/what-is-the-platform/what-is-the-platform)  to Data Processing Pipelines. 

2. In the Develop sections, please change the menu item  "Tertiary Portal Development Guide" to "Analysis Applications"
Thanks!

**Comment by jodihir** [comment]
@NoopDog (This is the same comment as from Sept 7 above) 
1. About section: please change the Secondary Analysis menu item (https://dev.data.humancellatlas.org/about/what-is-the-platform/what-is-the-platform) to Data Processing Pipelines.
2. Develop sections, please change the menu item "Tertiary Portal Development Guide" to "Analysis Applications"
Thanks!

**Comment by frano-m** [comment]
Hi @jodihir 

Listed below are markdown files with secondary or tertiary mentioned (some are href links that need updating):

`/about/what-is-the-platform/data-processing-pipelines.md` (3x secondary)
`/about/what-is-the-platform/data-store.md` (1x secondary, 1x tertiary)
`/contribute/what-to-prepare.md` (1x secondary) <-- this page not live
`/develop/development-guides/pipeline-processing-development-guides/contributing-a-pipeline-to-the-hca-dcp.md` (1x secondary)
`/develop/development-guides/pipeline-processing-development-guides/pipeline-development-guide.md` (2x secondary)
`/learn/userguides/data-processing-pipelines/file-formats.md` (2x secondary)
`/learn/userguides/data-processing-pipelines/qc-metrics.md` (2x secondary)
`content/contribute/overview/what-to-expect.md` (1 x tertiary)

**Comment by jodihir** [comment]
Hi @frano-m, Thanks very much! I will go through this list and fix instances that are in the text.  I assume that you and Dave will update the links, but let me know if I need to do something about those.

**Comment by NoopDog** [comment]
yes we will update the links. Thx

**Comment by NoopDog** [comment]
@jodihir Hi, I misspoke, can  you update the internal links please as we are not sure which page they are supposed to. Please reach out to me on slack if want to discuss.

**Comment by jodihir** [comment]
optimistically moving this to done...but (pessimistically) not closing the ticket..
