### ISSUE TITLE
Determine the layout for the Development Guides Overview page and order the menu on the left

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#130]
# Why
Is this layout the one we want to use and if so, we need to add the other guides to it.

https://dev.data.humancellatlas.org/develop/development-guides/development-guides-overview
Also, let's update the order of the pages on the left, creating sections.

**Comment by NoopDog** [comment]
@jodihir this is updated here for your review. Can you add the relevant subTitles to fill out the text? thanks!
https://dev.data.humancellatlas.org/develop/development-guides/development-guides-overview

**Comment by jodihir** [comment]
OK, this seems fine to leave as is.  

One last thing about the left menu, can you move "Ingest Data Brokers Development Guide" so that it's below the "Overview" and above "Pipeline Processing Development Guides" . Thanks.
