### ISSUE TITLE
Add text to Analyze page explaining relationship between portals and DCP data

### ISSUE THREAD

**Issue by adriennes** [HumanCellAtlas/data-portal-content#140]
# Why
As a user I would like to use the Analyze portals to analyze DCP data

# Definition of Done
 - [ ] Clearly explain what the relationship is between the portals and data, set user expectations

**Comment by NoopDog** [comment]
@TimothyTickle  @adriennes The text has been updated on ux-dev https://ux-dev.data.humancellatlas.org/analyze to indicate in a header over each list:

1. A brief description of the list.
1. That the projects are not built by HCA/DCP team.
1.  That you may contribute your own project to the registry. 

How do these updates look to you? Do you feel we need to additionally clarify the relationship between the HCA and these tools or specify further why they have been chosen for this list? 

Cheers,
D

**Comment by NoopDog** [comment]
@adriennes @TimothyTickle @eweitz 

One thing that came up on a recent call with Eric was to highlight that we have a registry by calling it a registry and introducing the noun on the site.

Eric is working on creating additional text on why the specific tools were selected for the registry and how handoff will work between the registry and selected tools.

I wanted to get feedback on modifying the top level text of the "Analyze" section to be "Analysis Tools Registry" to introduce the term and set context to where the user is.  We have mocked this below. 

Are folks ok with making this change? Or, what else might we call the registry? 


![Screen Shot 2019-01-08 at 10.26.27 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/00edcc7f-da8d-4df4-bc74-f88f002fa120)

Thanks, 
D

**Comment by theathorn** [comment]
@TimothyTickle @eweitz We will close this ticket unless you review/reopen in the next few days.

**Comment by eweitz** [comment]
@NoopDog, @theathorn, these updates look good to me.
