### ISSUE TITLE
Edit/clarify names of Analyze tabs

### ISSUE THREAD

**Issue by adriennes** [HumanCellAtlas/data-portal-content#141]
# Why
As a user I would like to understand the differences between the tabs in Analyze section

# Definition of Done
 - [ ] Rename tabs (Portals, Methods, Visualization components) to be more intuitive
- [ ] Add one sentence on each landing page summarizing what those tools/portals are

**Comment by theathorn** [comment]
@adriennes Do you have specific suggestions on which terms are more appropriate?

**Comment by adriennes** [comment]
@TimothyTickle  - How can we clarify the names of the "Portals", "Methods", and "Visualization Components" sections here?  

Some thoughts: 
- Are the "Portals" all for visualization? Some are analysis only, right? So perhaps we should be consistent in calling these just "portals" or "Analysis portals"? (within the tab, it currently says "Visualization Portals").
- "Methods" and "Visualization components" are both pieces of code to be used in your own analysis environment, correct? Could we use a common word to describe both, with "Analysis X" and "Visualization X", to show they're related? Could we call them "packages"?

**Comment by NoopDog** [comment]
@TimothyTickle I have updated the titles as per @adriennes suggestions on the ux-dev site.
https://ux-dev.data.humancellatlas.org/analyze

How do these look to you? Any updates or do you feel we can go with these?

Cheers,
Dave
