### ISSUE TITLE
Smart-Seq2 documentation - review

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#15]
Review the articles in the data portal for accuracy and completeness.  

SS2:
https://dev.data.humancellatlas.org/learn/userguides/data-processing-pipelines/smart-seq2-workflow-in-detail
Add Benchmarking information if applicable.

QC metrics section:
https://dev.data.humancellatlas.org/learn/userguides/data-processing-pipelines/qc-mertics

**Comment by kozbo** [comment]
@jishuxu Please review, thanks

**Comment by jodihir** [comment]
Moving to backlog for now.
