### ISSUE TITLE
Contribute section - UX review

### ISSUE THREAD

**Issue by gabsie** [HumanCellAtlas/data-portal-content#150]
# Why
As a data contributor I would like to include my data in the HCA, so that I am part of this international effort. For that reason, I want to know:

- if my data is suitable
- what the requirements are 
- what I need to do next
- when I will see it on HCA

# Definition of Done
 - When a contributor has a clear path of contribution of data to the HCA.

**Comment by gabsie** [comment]
I have revised the text, while using the same message.
I am pasting it first here for review (by data wranglers, Laura).
https://docs.google.com/document/d/1dtoHcMTvPZQBWq9RB954G4gXB4wFQNMoGtQauO2Frag/edit?usp=sharing

What I have done:

 - moved all content to only one page
 - suggest to remove the funny styling at the top, and be more in line with the rest of the pages
 - shortened the text to directly answer the questions a submitter might have at this point (see the criteria above around user goals)
 - bring forth the benefits to submitters more

All the best,
Gabby

**Comment by malloryfreeberg** [comment]
@gabsie So do you want to remove the "What to Prepare" subsection from the left navigation panel? And have all the text from the linked document on the Contribute > Overview page?

**Comment by gabsie** [comment]
yes, that makes sense. But I do want to check with Dave about styles that can accommodate some of my priority action points.

**Comment by malloryfreeberg** [comment]
Here is the [PR](https://github.com/HumanCellAtlas/data-portal/issues/273) to update the structural stuff.

Here is the [PR](https://github.com/HumanCellAtlas/data-portal-content/pull/166) to update the content stuff.

**Comment by NoopDog** [comment]
@malloryfreeberg @gabsie @claymfischer @lauraclarke the updates from above are implemented here https://dev.data.humancellatlas.org/contribute/overview/overview

**Comment by theathorn** [comment]
Related to: https://app.zenhub.com/workspace/o/humancellatlas/data-portal/issues/273

**Comment by malloryfreeberg** [comment]
Still waiting for icons to be added to the page (portal issue posted above)

**Comment by NoopDog** [comment]
@malloryfreeberg we can make a single image out of the 4 ions and insert it into the markdown there. 

We will also revert this page to use the standard markdown template and not the custom one that the other headings introduced.

We will use the current "tip" style to highlight the "contact us" call to action at the bottom as well.

Cheers,
D

**Comment by NoopDog** [comment]
@malloryfreeberg @gabsie we have:

1. Merged the pr.
1. Added made an image of the combined icons and added this to the content.
1. Updated the call to action at the bottom of the page with the "tip" style.
1. Updated all first and 2nd level headers to title caps.
1. Removed the redundant call to action mid document. 

I got into a bit of a wrestling match with git trying to merge this so can you please scan through the page and make sure it looks ok.

For any new changes to this section please create a new PR. 

Thanks and let me know if everything looks "OK".

Cheers,
D

**Comment by malloryfreeberg** [comment]
Looks great, @NoopDog !

There are still some incorrect links to dev environment instead of current (staging, in this case) environment

> Once submitted to the Human Cell Atlas, your data will be searchable in the **Data Browser**.

> Your data will also be available for use directly in **analysis applications** available through the Data Portal.

I think these are updates to the content I need to make to use relative instead of absolute paths. I will update that now and make a new PR.

**Comment by malloryfreeberg** [comment]
I think this is done! @gabsie if you are happy with the [page](https://staging.data.humancellatlas.org/contribute/overview/overview/) now, please close this ticket :)
