### ISSUE TITLE
Metadata Standards - UX review

### ISSUE THREAD

**Issue by gabsie** [HumanCellAtlas/data-portal-content#151]
# Why
As a data user and contributor I would like to discover and have a clear idea on metadata attributes that HCA uses, so I know how to interpret the data I use and use the right terms for data I contribute.

# Definition of Done
 - When users can easily find and make sense of the metadata attributes.

**Comment by malloryfreeberg** [comment]
@gabsie are there any specific actions you want take to address this issue?

**Comment by theathorn** [comment]
@malloryfreeberg Please review tickets added to this Epic.

**Comment by malloryfreeberg** [comment]
I think data-browser #241 does not belong linked to this Epic as it is not about the standards, it's about delivering metadata from the DS to the user.

**Comment by malloryfreeberg** [comment]
I think the other data-browser tickets (#131 and #434) and azul #552 also don't belong here as they aren't about displaying the metadata dictionary in the portal.
