### ISSUE TITLE
Change "Metadata Standards" tab name to just "Metadata"

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#152]
In the Learn section, remove the word "standards" from the "Metadata Standards" tab so it just says "Metadata".

**Comment by theathorn** [comment]
I raised this as https://app.zenhub.com/workspace/o/humancellatlas/data-portal/issues/271.
I think it's a portal rather than a content issue.

**Comment by NoopDog** [comment]
Thanks we should adjust the URLS as well.

**Comment by NoopDog** [comment]
@jodihir this is ready to review

**Comment by jodihir** [comment]
Looks good to me.
