### ISSUE TITLE
"Data Processing Pipelines" : Internal links are not working (404 error) 

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#164]
https://dev.data.humancellatlas.org/about/what-is-the-platform/data-processing-pipelines/

There are internal links each row of the table that don't work in the dev site. Here how they're formatted: 

Read more about the pipeline [here](/learn/userguides/data-processing-pipelines/smart-seq2-workflow-in-detail).

[Read more](/learn/userguides/data-processing-pipelines/optimus-prime-workflow-in-detail) about the pipeline.

**Comment by NoopDog** [comment]
@jodihir this is ready to review. It was just that the urls were old.
