### ISSUE TITLE
Help/FAQs need to be reviewed to better reflect content in user guides

### ISSUE THREAD

**Issue by adriennes** [HumanCellAtlas/data-portal-content#165]
# Why
As a user I would like to understand where documentation exists

# Definition of Done
 Update and review FAQs; make sure they reflect recent Zendesk questions from Preview Site

**Comment by jodihir** [comment]
HI @adriennes 
Can you review these things in the FAQ:
1. The second question about the kind of data in the HCA is a little confusing. This sentence "In the future, we will offer data releases that contain only healthy human samples." doesn't seems consistent with the sentence before it.
2. The link for the data use agreement goes to a page with no content. I think that's an old Terms and Conditions page?

**Comment by theathorn** [comment]
@adriennes Status on this review?
