### ISSUE TITLE
Updates needed on the Analysis Applications page of the Data Portal

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#169]
For this page: https://dev.data.humancellatlas.org/learn/development-guides/analysis-applications

1. In the Working with Ingest section it says:
"This does require authentication and would require contacting the ingest team."  Include some instruction about how to do that and what the ingest team needs to know.

2. The sections about Matrix Service, Hand-off, and Registry at the end say that instructions are "coming soon". Can we write some of those yet?

**Comment by jodihir** [comment]
Contact Ingest and Matrix service to make these updates.

**Comment by jodihir** [comment]
@rdgoite Can you get the information to add for the "Working with Ingest" section?

I contacted eweitz for help with the registry instructions.

**Comment by eweitz** [comment]
@jodihir, while fixing hyperlinks just now, I added [links to registry instructions](https://github.com/HumanCellAtlas/data-portal-content/blob/3b4803ae8885242781776374fee67635bd8075d3/content/learn/development-guides/analysis-applications.md#list-your-solution-in-the-registry).  They should appear on the website with the next deployment.  If more would help here for Methods Registry, please let me know!

**Comment by jodihir** [comment]
Thanks @eweitz!

**Comment by jodihir** [comment]
Added data-help email address to the Ingest section. Closing this ticket.
