### ISSUE TITLE
Highlight matrix service API 

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#170]
Now that the Request Expression Matrix button is on the browser, we can add some explanation of the matrix service to the user guides

**Comment by theathorn** [comment]
Documenting the Matrix Expression Service API would be more appropriate under the Develop section.

**Comment by brianraymor** [comment]
As Trevor notes, the Expression Matrix Service is a service with a REST API. We can easily duplicate the Data Store page and point developers to our README and Swagger page. I've updated the title to reflect that point. The Data Browser provides all the user facing interactions.
