### ISSUE TITLE
Limit the titles in the left nav to about 30 characters to keep them from wrapping for ease of reading. 

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#171]
![Screen Shot 2018-10-26 at 11.49.26 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/bc093b98-5e63-49b4-b9cd-c4d886597264)

**Comment by NoopDog** [comment]
I have gone ahead and updated most of the long titles so now the same section as above looks like this:


 ![Screen Shot 2018-10-26 at 6.40.02 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/7475dec9-b4e4-49ae-9229-1bdbbb0f3b49)

We can easily roll back or update any left nav content that need changing.

Cheers,
Dave

**Comment by jodihir** [comment]
@NoopDog, to change these titles in the nav, do I go into the front matter section and change the Title? (I want to shorten some titles in the the pipelines section of Learn guides)

**Comment by NoopDog** [comment]
@jodihir link menu names are currently edited by us in the sitemap in the portal repo. Can you add the list of names you want changed to this ticket  and we can update them.
