### ISSUE TITLE
Consider renaming "About" to "Platform"  and adding to the main navigation in the 2nd Position 

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#173]
The "About" section has a good overview in the "What is the Platform Section". It discusses the parts of the system and how they interrelate. 

However, this content is stuck over on the side under about/what is the platform and I feel is lost there.
Additionally, "about" is usually some foundational fluff with team members etc and usually can safely be ignored. 

I would like to recommend to bump the chance of discovering the "What is the platform" content greatly buy renaming About to "Platform" and placing this just after the "Explore" link in the header. 

So we would have something like

Explore Platform Contribute Learn Develop

I feel having the word "Platform" front in the header signifies that there is a "Platform" and helps sets the expectation that when you click on it there will be info about the "Platform".

**Comment by jodihir** [comment]
I'm fine with that. I'd prefer to see the Platform link first, followed by something like:
Explore Data
Contribute Data
Analysis Tools
Learn 
Develop

Down the road we may want to expand this menu to include links to a Forum, Blog, Events,...
I've seen all these topics as top menu items.

We can continue discussing :)..

**Comment by NoopDog** [comment]
Now redundant with other tickets.
