### ISSUE TITLE
Review content to add line breaks to make paragraphs smaller and add subheadings

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#174]
Many of the pages already follow this pattern but I thought it would be a useful exercise to find and update any that don't.

### Smaller Paragraphs
For the web paragraphs need to be quite small to be readable. Even the New York Times has many single sentence paragraphs.  A max of 3 or 4 sentences might be reasonable for us.

### More Subheadings
Additionally, using the smaller subheadings will help make the pages more scannable. 

### See What I Did There?
Yes I am trying to make this ticket an example of the kind of thing I am talking about. I am using sub-headings and making the paragraphs short. I hope this makes a convincing point!

### For Example
Here is a good existing example of a page that follows this pattern to see how the markdown is done.
https://dev.data.humancellatlas.org/about/what-is-the-platform/ingest-service

**Comment by jodihir** [comment]
Got it!  This is very helpful @NoopDog:  I will make updates to content (especially mine ;)).

**Comment by NoopDog** [comment]
Hi @jodihir can this be closed now?

**Comment by jodihir** [comment]
Leaving this ticket open as a reminder, as we update and write new content.

**Comment by kozbo** [comment]
update the Style guide with this info, then close this ticket
