### ISSUE TITLE
Review content to consistently use title caps for content section headers

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#175]
We have some pages that use title caps and some that use sentence caps for content headers

Lets prefer:

### Using Title Caps 

to

**Comment by jodihir** [comment]
Thanks @NoopDog! I will fix those as I review, and this is added to the style guide.

**Comment by NoopDog** [comment]
Hi @jodihir can this be closed now?

**Comment by jodihir** [comment]
@malloryfreeberg Should caps be added to sub-headers on Metadata structure and Design Choices articles? 
eg: for this page: https://dev.data.humancellatlas.org/learn/metadata/rationale
 Does 'Machine-readable formats' become 'Machine-readable Formats'
If we follow the style of this ticket there are a bunch of changes to make so I wanted to check with you first before making them.

**Comment by malloryfreeberg** [comment]
> @malloryfreeberg Should caps be added to sub-headers on Metadata structure and Design Choices articles?
> eg: for this page: https://dev.data.humancellatlas.org/learn/metadata/rationale
> Does 'Machine-readable formats' become 'Machine-readable Formats'
> If we follow the style of this ticket there are a bunch of changes to make so I wanted to check with you first before making them.

Hmm. This will require that we update the title capitalization in the documentation in the metadata-schema repo, which is what is imported by the portal to display here. 

I wonder if there is a way the Portal can programmatically capitalize headers like this? The metadata documentation is not the only documentation that gets pulled in by the Portal. If there is a code-based way to standardize the formatting in the Portal, I would prefer that to ensuring that all pulled-in documentation in the various repos has the same format as the Portal (this is difficult to maintain).

**Comment by jodihir** [comment]
@NoopDog Can we discuss this at our content meeting tomorrow?

**Comment by jodihir** [comment]
Looks done - closing this ticket
