### ISSUE TITLE
Fix the super long URLs to some of the content pages

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#176]
The data content outline is reflected in the URLS so we get some long URLS for pages that are 3 deep in the content and that have sections with long names. Review the URLS for shortening and also see the related ticket to allow short urls for the markdown driven  pages

**Comment by theathorn** [comment]
From @eweitz :

While drafting a poster abstract about the HCA Methods Registry, it occurred to me that the URLs for key areas of the HCA Data Browser could be refined for better branding.  

For example, the current Methods Registry URL is https://dev.data.humancellatlas.org/analyze/portals/visualization-portals.  The "/portals/visualization-portals" part is redundant and makes the URL unnecessarily long.  A shorter URL -- https://dev.data.humancellatlas.org/analyze -- would be more memorable and better for outreach material like blog posts, journal articles, posters, etc.

Here's a list of proposed shorter URLs to support:
Explore
Current: https://dev.data.humancellatlas.org/explore/
Proposed: no change

Analyze
Current: https://dev.data.humancellatlas.org/analyze/portals/visualization-portals/
Proposed: https://dev.data.humancellatlas.org/analyze

Contribute
Current: https://dev.data.humancellatlas.org/contribute/overview/overview
Proposed: https://dev.data.humancellatlas.org/contribute

Learn
Current: https://dev.data.humancellatlas.org/learn/overview/overview
Proposed: https://dev.data.humancellatlas.org/learn

Develop
Current: https://dev.data.humancellatlas.org/develop/development-guides/development-guides-overview
Proposed: https://dev.data.humancellatlas.org/develop

Does this seem worthwhile?  Dave and I agreed so at least for Methods Registry, and he's adding a task for that to the backlog, but I thought I'd run this slightly broader proposal by you.

**Comment by eweitz** [comment]
@theathorn, @NoopDog, some Methods Registry URLs still have repetitive parts, e.g.:

* https://dev.data.humancellatlas.org/analyze/methods/methods
* https://dev.data.humancellatlas.org/analyze/visualization-components/visualization-components

Could those be refined?  The other ones above look good!

**Comment by eweitz** [comment]
Nice, thank you Dave!

**Comment by NoopDog** [comment]
OK these changes will be deployed everywhere shortly. If the changes look ok to you please go ahead and close the ticket. @eweitz
