### ISSUE TITLE
Add a paragraph about the matrix service to the Data Browser page in the Learn/Intro section

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#180]
Now that the data browser has an option to request an expression matrix, we should include information about what a user gets when they click that button.  The information can be added to this page:

 https://dev.data.humancellatlas.org/about/what-is-the-platform/data-browser

**Comment by brianraymor** [comment]
@jodihir - https://dev.data.humancellatlas.org/about/what-is-the-platform/data-browser - does not resolve for me. Do you mean - https://dev.data.humancellatlas.org/about/platform/dcp/data-browser?

**Comment by jodihir** [comment]
Yes, that's the page.  I think we just want to add here that there IS a matrix service and what it provides to the user. It was pointed out in the content team jamboree (at the F2F) that this page is a little more "how-to" then it should be for an About section. Maybe we need to move some of this to a separate page in the Learn section to serve as a guide for using the data browser, and we can add details of using the matrix service there.

**Comment by theathorn** [comment]
I believe the correct page is now: https://dev.data.humancellatlas.org/about/platform/dcp/data-browser/

**Comment by NoopDog** [comment]
@theathorn lets close this one as well and replace with  the updated portal and DSS user guides.
