### ISSUE TITLE
Remove or Hide the Optimus Prime doc in the User Guides

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#186]
We don’t have the Optimus pipeline available yet so can you temporarily remove/hide this doc (in the Data Processing Pipelines section of the Learn User Guides) for the time being until the pipeline is ready for use (in a few months)? 

Remove this from the left menu so it can't be found. I will search for links in other docs that need to be removed.

**Comment by NoopDog** [comment]
@jodihir this is ready to review here:
https://staging.data.humancellatlas.org/develop/development-guides/pipeline-processing-development-guides/overview-pipeline-processing-development-guides

Thx,
D
