### ISSUE TITLE
Have unique titles for pages in Web Browser tabs

### ISSUE THREAD

**Issue by matthewspeir** [HumanCellAtlas/data-portal-content#189]
# Why
As a user, I would like to have multiple pages from the Data Portal open at the same to read multiple pages and not forget what web browser tab is what.

# Definition of Done
 - Pages have unique titles, e.g. 'HCA Data Portal - About Visualization Components'.

**Comment by lauraclarke** [comment]
Quick note, if you do this put the unique information first e.g "About Visualization Components - HCA Data Portal" as tab titles very rarely put more than the first 15 characters on them so if they all start with HCA Data Portal you still won't have unique names

**Comment by NoopDog** [comment]
@frano-m I think this should be simple now that we have done the gatsby upgrade. Lets discuss.

**Comment by NoopDog** [comment]
@theathorn this is deployed to prod.
