### ISSUE TITLE
Add DNAstack as an application

### ISSUE THREAD

**Issue by mfiume** [HumanCellAtlas/data-portal-content#19]
# Why
DNAstack's a secondary and tertiary analysis provider. We support running private and public workflows written in WDL/CWL and would like to enable the community to run these on HCA data.

# Definition of Done
 - [ ] List DNAstack as an app on the visualization portal page
 - [ ] Integrate DNAstack with the portal such that collections of data from HCA can be imported

**Comment by eweitz** [comment]
Hi @mfiume!  Could you fill out the information below?  We'll use this in your portal's listing in the registry.

* Title of tool
* URL of tool
* 2-3 sentence description
* Who to attribute

And if you'd like:
* Contact info to display
* Logo or screenshot

**Comment by eweitz** [comment]
@mfiume, DNAstack is now listed as a portal at https://dev.data.humancellatlas.org/analyze/portals/visualization-portals/.  We'll ping this issue when the "hand-off" mechanism to import HCA data in tertiary portals is ready.
