### ISSUE TITLE
Update content of the About section

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#190]
Update content based on the comments from the breakout session, here: https://docs.google.com/spreadsheets/d/1cqdKXsRys9yI4jDPQk_78H2YmHgYt3dHmOUUhtpqcjc/edit#gid=1734732196 (comments in rows 1-8)
Also need to review content of Pipelines section with the goal of moving it to Learn.

**Comment by theathorn** [comment]
Move "Ingest Service", "Data Store", and "Data Browser" sections to Learn/Introduction.
"Data Processing Pipelines" has already been moved.

**Comment by NoopDog** [comment]
HI @jodihir can this be closed? 
We need to add the "About the HCA" but that is covered by a different ticket.
I think we have done all the tings we wanted to do with "About" so far.
