### ISSUE TITLE
Remove Learn Overview page and use the relevant content for a new page in the About section

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#193]
This needs discussion, but as we revisit the scope of the "About " section I propose we move the contents of the Learn Overview to a page in About that describes the portal itself.  This could include short descriptions of how the portal supports:
-Data contribution (Ingest, metadata standard)
-Finding and downloading data (browser, matrix service, CLI)
-Developer services (portability service, guides, vignettes)
-Handoff service (should we call it that?) to community tools and applications

The tabs in About could be: 
About the DCP Platform
About this Portal

**Comment by theathorn** [comment]
Is this complete?
