### ISSUE TITLE
Development Guides Overview page

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#194]
left menu titles inconsistent with main panel titles (e.g. "Processing Pipelines" vs "Pipeline Processing.." Drop "Development Guides" from main panel titles and reconcile titles? Drop "your" from "Analysis Applications".

**Comment by jodihir** [comment]
I'm wondering if we should drop this page like we're thinking about doing with the Learn Overview?

**Comment by theathorn** [comment]
Is this complete?

**Comment by jodihir** [comment]
We removed the Overview page so we can close this.
