### ISSUE TITLE
Sitemap Updates

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#195]
### What problems are we trying to solve?

Now that we have a bit of content developed and are clearer on our content lets take a step back and see how we might improve the organization of the content to improve the organization and discoverability of the documentation. Specifically: 

1. We have duplicate content. 
1. We have content about the content (e.g. This section will tell you that...)
1. We have no obvious Intro/Overview/Cave Entry section. 
1. It is not clear what the difference is between "Learn" and "Develop".
1. It could be more obvious how to get help.

### Proposed Updates

1. Replace "About" with "Help in the upper right.  - About is usually background material that can be ignored or glossed over. The top right is a high visibility section that I feel could be better used to introduce the "Help / Faq.

1. Remove "About/Overview' section- this is redundant with the home page except for the "Mission" -OK

1. Remove the "Learn/Overview" section - this content is about the content instead of being about some portion of the HCA/DCP. -OK

1. Remove "Develop/Development Guides/Overview - this basically duplicates the left nav of this section. - OK

1. Add "Begin" as a new top level section to give an overview/intro of the HCA and DCP. Use the "About/What is the Platform" section from the about section to seed the new "Intro"section and function as our cave entry. 

1. Merge "Develop" into "Learn" and add the developer guides and developer docs sub sections section under "Learn" - OK

1. Link the "Learn More" link on the homepage to the new "Begin" section.

### Updated Sitemap
The updated sitemap would then be:

```
Begin
   Platform
   Help & Faq
   Contact
Explore
Contribute
Analyze
   Portals
   Methods
   Visualization Components
Learn
   Metadata
   User Guides
   Developer Guides
   Developer Docs
Help
```
### Demo Site: https://ux-dev.data.humancellatlas.org/
To enable feeling and exploring the proposed updates they have been  implemented on the dev-ux environment. 

https://ux-dev.data.humancellatlas.org/

Stick with Verbs
Do the OK from above.
Research more on the distinction between, "Cave Entry" vs About.
Goal for next meeting 
Monday, but have basic feedback by Friday.

**Comment by malloryfreeberg** [comment]
> * Rename "Learn" to "Guides" and place the "User Guides" and "Developer Guides" under here.
> * Rename "Develop" to "Docs" and place the Metadata Dictionary and Developer Docs here.

Could these two sections be combined? In my mind, Docs are a subset of Guides.

**Comment by NoopDog** [comment]
Hi @malloryfreeberg yes, That one is also on my radar. I added it to a new "Additional Options" section. above. Thanks for the suggestion.

**Comment by NoopDog** [comment]
The proposal above and the https://ux-dev.data.humancellatlas.org/ site have been modified with feedback from the last content meeting.  We will be reviewing again at today's UX meeting.

Cheers,
D

**Comment by NoopDog** [comment]
The outcomes of today's UX meeting are:

1. We agreed to implement several of the changes marked with  "OK" above.
1. We agreed to do more research about the distinction between "About" vs "Intro" sections 
1. We will keep the "verb" headings for the moment, but will consider nouns once we decide on teh full set of top level nav items.

I have converted this issue to an epic and linked tickets to the items agreed upon so far.  

Note that the result of deleting the Learn/Overview section is that Data Life Cycle and Data Use Agreement need a home.  We will move these under About/Platform for now until the above items are settled.
