### ISSUE TITLE
Write About the Human Cell Atlas (HCA) section

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#205]
We have an "About the DCP" paragraph under About.
We need a similar paragraph for the HCA.

**Comment by NoopDog** [comment]
Hi @adriennes if you want to paste the content in here as markdown we can get it added to the site.  Cheers and Thanks, D

**Comment by adriennes** [comment]
@NoopDog  - I think we need to make two subpages within this section: 
- About the Human Cell Atlas
- About the Data Coordination Platform
We should also move the Attributions section under "About" as a third subpage. 

Proposed text below for each section: 
About the Human Cell Atlas: 
The Human Cell Atlas (HCA) is a collaborative community of international scientists.  Our mission is to create comprehensive reference maps of all the cells in the human body as a basis for both understanding human health and diagnosing, monitoring, and treating disease.  

The HCA registry has more than one thousand member scientists from hundreds of institutions around the world.  The project is steered and governed by an Organizing Committee,  co-chaired by Aviv Regev and Sarah Teichmann.  

To learn more about the HCA, visit https://www.humancellatlas.org/.  

To join the HCA community, you can register on this page. [https://www.humancellatlas.org/joinHCA]

About the Data Coordination Platform:

The Human Cell Atlas Data Coordination Platform (HCA DCP) is an open source, cloud-based platform developed to organize, standardize, and make accessible the data that constitute the Human Cell Atlas.

This platform has been constructed by a consortium of scientists, engineers, and designers from the Chan Zuckerberg Initiative (CZI), the European Bioinformatics Institute (EBI), the Broad Institute (Broad), and University of California, Santa Cruz (UCSC).

The HCA DCP wouldn't be possible without community involvement.  The easiest way to get involved is by helping us with feedback and testing.  Learn more on the Contact page [https://prod.data.humancellatlas.org/contact].  We also encourage you to contribute your data or analysis portals and methods.  Learn more on the Contribute page [https://prod.data.humancellatlas.org/contribute].

**Comment by NoopDog** [comment]
HI @adriennes your changes above for:

1. About the DCP
1. About the HCA

are deployed to all environments.

https://prod.data.humancellatlas.org/about

I will create a separate ticket to move the attributions.

Cheers,
Dave

**Comment by adriennes** [comment]
Looks good!  I'm fine to close.
