### ISSUE TITLE
Reword Ingest Service "Process" section

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#207]
@theathorn commented on [Fri Dec 07 2018](https://github.com/HumanCellAtlas/data-browser/issues/394)

Clarify between "data" and "metadata" usages.

**Comment by malloryfreeberg** [comment]
I have gone through and updated the [Google doc](https://docs.google.com/document/d/1GUX6zWlPx_ZWc-GLr_8cpX2qEjtdW4pQTTw27edhPTg/edit?ts=5c0ab574#heading=h.dv5k48j4gnjo) with the text of the Ingestion Service section (and a bit of the Introduction section).
