### ISSUE TITLE
Add sub-sections under Guides

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#208]
In Guides add sections for:

 - [x] Installing the HCA CLI
 - [ ] Using the Data Browser to Access Data
 - [ ] Using the CLI to Access Data
 - [ ] Using the Data

**Comment by NoopDog** [comment]
@theathorn I feel this is best replaced by adding an updated data browser user guide and separate DSS user guide. Lets close this and replace with new ticketss.
