### ISSUE TITLE
Add sub-sections under Contribute

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#210]
Proposed sub-sections:
 - Contributing Data
 - Contributing Pipelines
 - Contributing Data Consumer Vignettes

**Comment by jodihir** [comment]
Also, include this sub-section:
Contributing portals and packages

**Comment by NoopDog** [comment]
@frano-m we can start with stub docs for each of these that don't yet go in the site map. Thanks.

**Comment by NoopDog** [comment]
Separated this into separate tickets e.g #238 and #239
