### ISSUE TITLE
Create a Glossary for the portal

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#212]
This is an action item from the F2F at the Broad, November 2018

**Comment by kozbo** [comment]
add the list of words that should be in the glossary here, and then we will  consider the need for a glossary

**Comment by jodihir** [comment]
DCP glossary items can be put here: https://docs.google.com/spreadsheets/d/1KaRWiAIVs5BETqwhQ7BI0B65EWSjCmw-RlbGdSjKLGI/edit#gid=0

(This doc is in the DCP communications and outreach folder.)

**Comment by malloryfreeberg** [comment]
There is another list of DCP glossary items [here](https://docs.google.com/spreadsheets/d/1yOjsfZptQJiuagVLpy4xlNnL9-yKK87gTs5gWIare2c/edit#gid=0). Should this and the doc Jodi referenced ([here](https://docs.google.com/spreadsheets/d/1KaRWiAIVs5BETqwhQ7BI0B65EWSjCmw-RlbGdSjKLGI/edit#gid=0)) be reconciled?

**Comment by jodihir** [comment]
Yes, let's do that!  I didn't realize we already have that doc. Thanks @malloryfreeberg.

**Comment by jodihir** [comment]
I added the words from [this doc](https://docs.google.com/spreadsheets/d/1yOjsfZptQJiuagVLpy4xlNnL9-yKK87gTs5gWIare2c/edit#gid=0) to [this doc](https://docs.google.com/spreadsheets/d/1KaRWiAIVs5BETqwhQ7BI0B65EWSjCmw-RlbGdSjKLGI/edit#gid=0): so it should be possible to just use the latter.  I also went through all the charters and pulled out those definitions and added those.

**Comment by jodihir** [comment]
Here is the doc to work from: https://docs.google.com/spreadsheets/d/1KaRWiAIVs5BETqwhQ7BI0B65EWSjCmw-RlbGdSjKLGI/edit#gid=0
Closing ticket
