### ISSUE TITLE
BioTuring Single Cell Browser

### ISSUE THREAD

**Issue by bioturing** [HumanCellAtlas/data-portal-content#217]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://prod.data.humancellatlas.org/analyze/portals,
please provide the following package metadata.

Required:
- Tool title: BioTuring Browser
- Contact name: Son Pham
- Contact email: sonpham@bioturing.com
- Who to attribute: BioTuring Team
- Portal URL: https://bioturing.com/product/bbrowser
- 2-3 sentence description: BioTuring Single Cell Browser combines modern data visualization techniques, statistical machine learning toolboxes, and a rich knowledge base to create a unique platform for single cell data analytics. 

Optional:
- Logo or screenshot: (Attach to this GitHub issue.)
![screenshot](https://user-images.githubusercontent.com/30481444/50866573-47dd0a00-135f-11e9-90db-33811f2c4f89.png)

**Comment by eweitz** [comment]
Thank you, @bioturing!  

I've created a listing for your portal in our `ux-dev` branch ([commit](https://github.com/HumanCellAtlas/data-portal-content/commit/3a05a1eeaaea2fa806d70a326a3e2258a4de36da)), so it should be available under https://prod.data.humancellatlas.org/analyze/ soon.
