### ISSUE TITLE
Order of portals and packages

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/data-portal-content#223]
# Why
As a user I would like to know why portals and packages are ordered the way they are in the Data Portal.

It is unclear why the portals and packages are ordered the way they are, and we don't want to introduce any bias in which tools are better than others based on their ranking in the list.

# Definition of Done
 - [ ] Decide ordering scheme of analysis portals, methods packages, and visualization packages (abc?)
- [ ] Implement ordering scheme

**Comment by malloryfreeberg** [comment]
@adriennes @gabsie @eweitz Do you have any insight into the best way to order these portals/packages?

**Comment by eweitz** [comment]
The current ordering basically reflects when the product was added to its respective list.  That seems relatively unbiased, but not useful.  

Better ordering criteria could incentivize developers to fulfill "optional" standards defined in [registry submission templates](https://github.com/HumanCellAtlas/data-portal-content/tree/master/.github/ISSUE_TEMPLATE) -- best practices that augment our minimum requirements.

Ideas for more useful default sorting criteria, mostly pulled from optional standards:

Portals:
* HCA handoff support; will be more relevant when such HCA handoff services are ready
* Open source 
  * If so, code pulse -- e.g. when was the most recent release?

All packages:
* Code quality
  * Continuous integration.  Build badge present?  Passing?
  * Code coverage metrics.  Coverage badge present?  Percent covered?
* Code pulse

Method packages:
* Benchmark dataset

Visualization packages:
* Mashup

These are just strawperson proposals.  @jlchang has deeper insight on methods, which present more complexity for ordering criteria than visualizations.  She is also preparing a document that gives more context to package standards.

Implementing more useful ordering would likely require engineering work in [HumanCellAtlas/data-portal](https://github.com/HumanCellAtlas/data-portal).  So it'd be worth looping in @NoopDog.

**Comment by eweitz** [comment]
Alphabetical sorting is implemented, and should appear in the next deployment.

**Comment by NoopDog** [comment]
I just alphabetized the order of the left navs as well and that is deployed to prod.

**Comment by NoopDog** [comment]
@malloryfreeberg will give  you the honor of reviewing and closing this. This is all deployed to prod.

https://prod.data.humancellatlas.org/analyze

Cheers,
D

**Comment by malloryfreeberg** [comment]
LGTM!

Thanks @eweitz and @NoopDog :)

It sounds like an ordering based on a badge system or another quality standard would be really cool and also meaningful (more meaningful than just abc order). Admittedly, I'm not closely following the portal and package development work, but I'd be very interested to hear about the package standards and how that could be incorporated into the ordering to reward "good" community behavior :)
