### ISSUE TITLE
Review the Analysis Applications doc, in Development Guides, and change title

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#224]
This document is more of an Overview of what the developer can do within the DCP. Let's decide if this doc is still up-to-date and consistent with the rest of the info in this section and whether it can be the introduction to this section.

**Comment by kozbo** [comment]
what is the core message of this page?  Identify that and then edit.

**Comment by jodihir** [comment]
@kozbo @malloryfreeberg @theathorn Can you check if the information in this doc is:
- current
- useful, as an overview for Developers
Should we make it an Overview/introduction in the Development Guides section, rather than an Analysis Applications page?

**Comment by malloryfreeberg** [comment]
1. The content of this page is definitely more than just "Analysis Applications", so either the name of the page needs to change (perhaps to Overview/Intro) or the scope of the content needs to be more focused on just analysis bits. 
1. The "Examples" section describing the Consumer Vignettes seems out of order. The other topics appear to be ordered by the data lifecycle (submit, store, pipelines, matrix, portals), but the consumer vignettes (I think) are mostly related to post-primary data submission? The "Examples" section could be moved further down.
1. There is a bit of duplication with some of the topics on this page and other pages in the Dev Guides section. e.g. there is a "Working with Ingest" section, but also an "Ingest Data Broker" section in the left-hand panel. Do we need both? If yes, the section on this page should link to the Ingest Data Brokers section?
1. In the "Learning More About Metadata" section, the first link should point to the Metadata Dictionary in the Portal, not a GH page.
1. The title "Finding Packages For Your Solution" is not very clear - what kind of "package"? Are these the tertiary portals? What is meant by "Your Solution"? 
1. I think the "Listing Your Solution In The Registry" is related to the "Finding Packages" section? Could this be simplified to just "Registering your Solution"?

As a general note, I'm not sure what the term "Solution" means in some of these descriptions. What solutions are being provided? What are the problems that these solutions are being presented for? Are we actually talking about the tertiary portals here? If so, we shouldn't use the term "solution" as what is really being provided is access to research tools. The HCA DCP isn't "solving" anything, it's "enabling" scientific research. I get a strong corporate vibe from some of the copy, which I don't think is the tone we want to take.

Happy to actually do some edits if people feel the same way. I don't want to step on anyone's toes if I'm out of line with my opinion :)

**Comment by jodihir** [comment]
Thanks so much for reviewing this @malloryfreeberg! I don't think any toes would be stepped on if we edit this, so please go ahead and do that. We need to make our documentation consistent and up-to-date across the site, which is challenging with the platform in development and multiple writers. 

I think "Solutions" is being used here generally, to describe tools, APIs, portals, etc. that are either being created by the developer reading this doc or have been created by the DCP to address some need. We can change that word (or use it less and more specifically). I agree, we don't want a corporate vibe...we just want to encourage and support developers..
