### ISSUE TITLE
Add 2 new docs about Methods Registry to the portal

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#229]
# Why
Jean Chang has asked us to add two new pages about the Methods Registry to our portal content.
We need to decide where these go: in the Analyze section or the Contribute section.

# Definition of Done
Google docs have been converted to Markdown in our CMS and are visible on the portal.

**Comment by jodihir** [comment]
Here are the links. Note that I haven't edited these yet; I can do it now or after you convert to markdown.  Let me know what you prefer.

Registry package submission support:
https://docs.google.com/document/d/1aqQM9tfrGNYGTLd356KilMSHsNGx_v95MXcoq8lGowk/edit?ts=5c51f799#heading=h.gczluy2p21aa

Methods Registry Standards Overview:
https://docs.google.com/document/d/14uDSNlNDrWOuRzmwd8Wnyuln8ky7RP3Zfb5LEM9B7tI/edit

**Comment by NoopDog** [comment]
HI @frano-m lets create two new pages for the "Contribute Section" so the contribute will look like:

Contributing Data
Contributing Analysis Tools (this is the registry package submission support linked above)
 . . . . Analysis Tools Standards (This is the methods registry standards overview )

Please create the stub docs, copy in the docs as markdown and link to the site map.

Thanks!
