### ISSUE TITLE
Add HCA Dataset Suitability Policy to Contribute Data section

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/data-portal-content#230]
# Why
As a user I would like to know what data the HCA is accepting in order to make an informed decision about whether I can/should/want to contribute data the the HCA.

# Definition of Done
- [x] A draft of the HCA Dataset Suitability Policy content 
- [x] Draft approved by Oversight to go on the portal
- [x] The approved HCA Dataset Suitability Policy content viewable in the portal

**Comment by theathorn** [comment]
@malloryfreeberg Who would write this policy?

**Comment by malloryfreeberg** [comment]
The policy is written [here](https://docs.google.com/document/d/1U7S9EsDPgxeEBuiONmyUorU2k8oNH-4CoM6JN9D5RHU/edit). 

I think we need a shorter version for displaying in the Portal. And this shorter version will likely need approval by the Oversight Committee (or similar group). You can assign me an AI to draft the short proposal and then circulate for approval.

**Comment by jodihir** [comment]
I assigned it to you.  Do you want to move this out of the backlog, or leave it there for now?

**Comment by malloryfreeberg** [comment]
@gabsie

**Comment by malloryfreeberg** [comment]
@gabsie and I are working on this now, so I moved it to In Progress.

**Comment by malloryfreeberg** [comment]
Draft is [here](https://docs.google.com/document/d/1DKwV2KidfaYL6ffwcdDreeyBMpVjK0STkJJzZYo0buk/edit#). Requesting to bring it up on PM call tomorrow for approval from Oversight.

**Comment by malloryfreeberg** [comment]
Draft was put in front of oversight on Mar 18. Oversight will give feedback by next meeting (Apr 1).

**Comment by theathorn** [comment]
Current state @malloryfreeberg ?

**Comment by malloryfreeberg** [comment]
There is an open PR in data-portal-content for this content to be added to the site. Awaiting a review from Gabby and/or Adrienne.

**Comment by malloryfreeberg** [comment]
The corresponding [PR](https://github.com/HumanCellAtlas/data-portal-content/pull/278) has been merged.

Happy to iterate over content in the future based on user feedback.
