### ISSUE TITLE
Bug in automatic title casing

### ISSUE THREAD

**Issue by eweitz** [HumanCellAtlas/data-portal-content#233]
Package titles are being unexpectedly uppercased in Analysis Tools Registry detail pages.  For example,  per its [documentation](https://github.com/igvteam/igv.js#igvjs), the title in https://prod.data.humancellatlas.org/analyze/visualization/igv should be "igv.js", not "Igv.Js".

Relatedly, titles in other pages like https://prod.data.humancellatlas.org/contribute/analysis-tools-registry differ in casing between the page itself ("Contributing To The Analysis Tools Registry") and the navigation panel at left ("Contributing to the Analysis Tools Registry").  Note how "to" and "the" are lower case in the latter, as is conventional with [title case](https://en.wikipedia.org/wiki/Capitalization#Title_case). 

Libraries like https://github.com/gouch/to-title-case seem promising for general titles.  For special titles like those for software, it might be best to not automatically change their case.

**Comment by NoopDog** [comment]
@eweitz this should be fixed in prod. Can you confirm? Cheers and Thanks, D

**Comment by eweitz** [comment]
Confirmed!
