### ISSUE TITLE
Update Contribute/Analysis Tools to match the "Analysis Tools Registry" Title, Content Guide and Tone. 

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#237]

**Comment by NoopDog** [comment]
@jodihir I have updated the title caps and the outline headings. Is there more you feel needs to be done to these pages or can we close this ticket? Thanks! D

**Comment by jodihir** [comment]
I'm closing this ticket and will ask Jean to review/finalize these pages.  I'm not sure if she'll have more content and/or edits to suggest - we can do that in a separate ticket.
