### ISSUE TITLE
Add "Contributing Vignettes" section to the contribute section. 

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#238]
We need a contributing vignettes as its own page in the contribute section.
This should cover a brief overview of what the vignettes are, were the repository is and how to contribute. 

Proposed starter text:

## Contributing Vignettes

The HCA maintains a [repository](https://github.com/HumanCellAtlas/data-consumer-vignettes) of "Data Consumer Vignettes" that are Python scripts, Jupyter notebooks etc. that show how to access and use the HCA data. We welcome community submissions to the vignettes repository. 

To make a submission please create a pull request against the data-consumer-vignettes repository.

**Comment by NoopDog** [comment]
@frano-m can you create a stub doc for this but leave out of the nav, Thx.

**Comment by jodihir** [comment]
Let's discuss the content of this page with TJ, who is working on vignettes and will be coming to our team meetings.

**Comment by NoopDog** [comment]
@jodihir I have made very basic holding page content in this ticket. Do you think we need additional content before we make a basic page and make it live?

**Comment by jodihir** [comment]
@NoopDog I can't find the basic holding page you're talking about.  Can you point me to it?

**Comment by NoopDog** [comment]
Hi Jodi, sorry the page is not created yet. The text I was referring to is at the top of this ticket.

**Comment by jodihir** [comment]
Ah, got it!  We can ask TJ for her thoughts at the content team meeting next week, but if you want to make it live now it seems fine to me, and we can update it later.
