### ISSUE TITLE
Add a Contributing Pipelines section to the "Contribute" section.

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#239]

**Comment by NoopDog** [comment]
@frano-m can we get a stub doc for this as well but leave out of the site map. Thx. D

**Comment by NoopDog** [comment]
@jodihir who can write up a very basic overview for this one that we can then iterate on? Need just enough to go live with.

**Comment by jodihir** [comment]
I think you can move this doc: 

https://prod.data.humancellatlas.org/learn/development-guides/pipeline-processing-development-guides/contributing-a-pipeline-to-the-hca-dcp

out of the Development Guides section and put the content int a new doc in the Contribute section. Does that sound OK?
