### ISSUE TITLE
Edit of content for tone

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#24]

**Comment by jodihir** [comment]
As documentation is developed Gabby and I will start reading through it to assess if tone and styles are reasonably similar so the user experience with our documentation is smooth and straightforward. We will also try to make sure the information is consistent across the boxes.  We'll likely enlist others to help as more documentation is completed.

**Comment by jodihir** [comment]
I've gone through all but the Develop section, which will be next; I'm making tickets to address more urgent issues.

**Comment by jodihir** [comment]
All pages reviewed as of 10-25-18. Closing ticket (moving forward we can make individual tickets for page improvements when needed).
