### ISSUE TITLE
New package: infercnv

### ISSUE THREAD

**Issue by GeorgescuC** [HumanCellAtlas/data-portal-content#261]
- Tool title: inferCNV
- Contact name: Christophe Georgescu
- Contact email: cgeorges@broadinsitute.org
- Who to attribute: Brian J. Haas, Christophe H. Georgescu, Maxwell P. Brown, Timothy L. Tickle, Livnat Jerby, Matan Hofree, Itay Tirosh, Aviv Regev
- Method-ready Docker image URL: docker pull singlecellportal/infercnv:0-99-5
- Code repository URL: https://github.com/broadinstitute/infercnv
- Affirm code is free and open source with license available in code repository: [x] (fill in as [x] to affirm)
- Language: R
- Upstream registry URL: Submitted to bioconductor on 03/13/2019
- Test data location: in docker container in /inferCNV/example
- Basic command line usage: 
./scripts/inferCNV.R \
     --raw_counts_matrix="../example/oligodendroglioma_expression_downsampled.counts.matrix" \
     --annotations_file="../example/oligodendroglioma_annotations_downsampled.txt" \
     --gene_order_file="../example/gencode_downsampled.EXAMPLE_ONLY_DONT_REUSE.txt" \
     --ref_group_names="Microglia/Macrophage,Oligodendrocytes (non-malignant)" \
     --cutoff=1 \
     --out_dir="output_cli" \
     --cluster_by_groups \
     --denoise
- Command to validate installation:
docker run -v ${PWD}:/data -w /data --rm -it singlecellportal/infercnv:0-99-5  Rscript /inferCNV/scripts/infercnv_validate.R
- Short description: InferCNV is used to explore tumor single cell RNA-Seq data to identify evidence for large-scale chromosomal copy number variations, such as gains or deletions of entire chromosomes or large segments of chromosomes. This is done by exploring expression intensity of genes across positions of the genome in comparison to the average or a set of reference 'normal' cells. A heatmap is generated illustrating the relative expression intensities across each chromosome, and it becomes readily apparent as to which regions of the genome are over-abundant or less-abundant as compared to normal cells.

[Optional](https://prod.data.humancellatlas.org/contribute/analysis-tools-registry#optional-fields-for-methods-and-visualizations):
- Long description: InferCNV is used to explore tumor single cell RNA-Seq data to identify evidence for large-scale chromosomal copy number variations, such as gains or deletions of entire chromosomes or large segments of chromosomes. This is done by exploring expression intensity of genes across positions of the genome in comparison to a set of reference 'normal' cells. A heatmap is generated illustrating the relative expression intensities across each chromosome, and it often becomes readily apparent as to which regions of the genome are over-abundant or less-abundant as compared to normal cells.
InferCNV provides access to several residual expression filters to explore minimizing noise and further revealing the signal supporting CNV. Additionally, inferCNV includes methods to predict CNV regions an
InferCNV is one component of the TrinityCTAT toolkit focused on leveraging the use of RNA-Seq to better understand cancer transcriptomes.
- Build badge URL: https://travis-ci.org/broadinstitute/infercnv.svg?branch=master
- Logo: https://raw.githubusercontent.com/wiki/broadinstitute/infercnv/images/infercnv.logo.png
- Screenshot: https://raw.githubusercontent.com/wiki/broadinstitute/inferCNV/images/infercnv.png
- Implementation of this tool in an active portal: https://github.com/broadinstitute/single_cell_portal/wiki/Running-inferCNV
- Benchmark dataset: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE70630

**Comment by jlchang** [comment]
@NoopDog [details page](https://github.com/HumanCellAtlas/data-portal-content/blob/master/content/analyze/methods/infercnv.md) for this Method is ready.

Please add inferCNV to sitemap as a listing for Analysis Tools Registry in the Methods section

**Comment by jlchang** [comment]
@NoopDog Is there more information needed to add this method to the sitemap as a listing for Analysis Tools Registry?

**Comment by NoopDog** [comment]
Hi @jlchang No, I think we have what we need. Sorry this fell of the radar. Will get this prioritized.  Thx

**Comment by NoopDog** [comment]
How does this look:
https://dev.data.humancellatlas.org/analyze/methods/infer

**Comment by jlchang** [comment]
Looks great! Many thanks.

**Comment by NoopDog** [comment]
This is deployed to prod https://prod.data.humancellatlas.org/analyze/methods/infer
