### ISSUE TITLE
Nit in title for Optimus pipeline documentation

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/data-portal-content#272]
![image](https://user-images.githubusercontent.com/9449764/56065172-18fd7800-5d42-11e9-99b7-7141d3b91a63.png)
The pipeline is just called `Optimus`, not `Optimus Prime` it's also in the URL https://prod.data.humancellatlas.org/pipelines/hca-pipelines/data-processing-pipelines/optimus-prime-workflow

Thanks!

**Comment by NoopDog** [comment]
Thanks @kbergin will let you know when this is fixed.

**Comment by NoopDog** [comment]
@kbergin this is on dev for your review.
https://dev.data.humancellatlas.org/pipelines/hca-pipelines/data-processing-pipelines/optimus-workflow

Cheers,
Dave
