### ISSUE TITLE
Rename "Community Pipelines" to "Develop Pipelines" 

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#274]
The docs in this section are not really about community pipelines, and Tim and Kylee requested that we not use that title. They would prefer we name the section Pipeline Development (or Develop Pipelines, Developing Pipelines - whatever fits best with our current naming style). 
Can you make that change soon please?  Thanks!

**Comment by NoopDog** [comment]
Sure I thought the pipelines developed outside of HCA were called "Community Pipelines". We can quickly change to Developing Pipelines and If it makes sense change it again soon to "Developing Community Pipelines" or "Developing your own Pipeline". 

I guess I am unclear about who would read this section and what they would be trying to do.
What wold the user goal be for the person reading these docs? 

The section starts out with:

```
We provide pipeline development guides, described briefly below, to help you design and build your own single cell data processing pipelines. When your pipeline is working, please consider submitting it to the DCP to help process data from the community. Email us at data-help@humancellatlas.org.
``` 
So it seems that this is for someone to create a pipeline and have this submitted to the HCA and run over all appropriate HCA data?

**Comment by NoopDog** [comment]
From slack conversation with @TimothyTickle  let's:

1. Rename to "Pipeline Development"

2. Have pipeline developer evaluate for feedback

3. If they say it can be improved we will, if they say to drop it we can stash it until we have users interested.

**Comment by NoopDog** [comment]
@frano-m can you rename the heading and then fix the paths to the sub docs please? Thanks!

**Comment by NoopDog** [comment]
@TimothyTickle @jodihir @kbergin This is on dev for your review:
https://dev.data.humancellatlas.org/pipelines/pipeline-development/processing-pipelines/pipeline-processing-development-guides

The heading and the URL of all the sub documents are updated. Thanks @frano-m 

Cheers,
Dave

**Comment by jodihir** [comment]
Looks good to me! Thanks @NoopDog

**Comment by kbergin** [comment]
Thanks, and to clarify the Q above, we are working on an RFC about enabling community members to do "contributed pipelines" but we don't want to suggest that that's an option to users until we have agreement on the process and requirements. I still think the section has value, given many users in the closed beta interviews weren't aware we were analyzing data with our own pipelines, they may be curious how we develop them.

It's possible more of this section should be reworded but for now it's probably fine.  Thanks for changing the heading!
