### ISSUE TITLE
Helpful content to reference in a DCP google site

### ISSUE THREAD

**Issue by happyimadesignr** [HumanCellAtlas/data-portal-content#28]
There is some great content here that would fit in our Data Portal About section and Reuse DCP Components section under Build. https://sites.google.com/broadinstitute.org/hca-dcp-org/home?authuser=0

**Comment by jodihir** [comment]
@gabsie @adriennes Do we want to add a page called "Our Values" to the About section? This could be the content for that type of page. In any case, I will add this wording to the Style Guide so that it is readily available to everyone in case it's useful.

**Comment by jodihir** [comment]
Closing this for now because the content has been copied in to the DCP style guide for use later.  When we decide to use it on a page about our values we can create a new ticket to develop that page.
