### ISSUE TITLE
About: Learn About Contributing

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#29]

**Comment by malloryfreeberg** [comment]
@theathorn @NoopDog Is this the page that this ticket is referring to: https://dev.data.humancellatlas.org/learn/userguides/contributing-data ?

**Comment by NoopDog** [comment]
https://github.com/HumanCellAtlas/data-portal-content/blob/master/content/learn/userguides/contributing-data/contributing-data-landing.md

**Comment by kozbo** [comment]
https://github.com/HumanCellAtlas/data-portal-content/tree/master/content/learn/userguides/contributing-data

**Comment by malloryfreeberg** [comment]
@willrockout @gabsie and I should discuss/do this. This is the only page that will provide any specifics/details about how users can contribute data at this point.

Information to include:
- Why would you want to contribute
- What you need to contribute (data, metadata, experiment type)
- Who to contact when you think you want to contribute data (data-help)

**Comment by malloryfreeberg** [comment]
@gabsie @willrockout I started a [branch](https://github.com/HumanCellAtlas/data-portal-content/blob/mf-contributing-data-landing/content/learn/userguides/contributing-data/contributing-data-landing.md) for this issue to add content to the [Learn About Contributing page](https://dev.data.humancellatlas.org/learn/userguides/contributing-data). Am definitely interested in your feedback of how this page will look. I know @gabsie has a mock up of what it should look like, so maybe we can schedule a call for later this week to go over what her plan is. I'm happy to do the actual implementation in the markdown.

**Comment by willrockout** [comment]
@malloryfreeberg Do you want to discuss this tomorrow morning? I can do 7 am if you and @gabsie have time.

**Comment by malloryfreeberg** [comment]
@willrockout yes! Calendar invite sent.
