### ISSUE TITLE
Search for metadata term

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/data-portal-content#292]
# A feature request

I'd like to be able to search for an attribute straight from https://prod.data.humancellatlas.org/metadata rather than having to scroll through to find what I need.

## Why
Many users don't care about the model and only see metadata as key value pairs. Therefore, I want to be able to use free text search to find similar attributes or specific programatic name e.g. 
`library_preparation_protocol.strand` to find the attribute I need.

The info I needed was actually there `Should be one of: "first", "second", "unstranded" or "not provided".` Perfect.

But I would like to be able to click a link through to the metadata schema too. This would be mainly useful when the enums get long or for ontology fields where looking at the detail is useful.

Even more amazing would be some usage stats on these too. How many projects have used that attribute? This would allow me to find some examples from actual projects so I know how to use it. (I'm asking too much now I know)

**Comment by NoopDog** [comment]
Hi @hewgreen thanks for raising this. We have this on our roadmap as data portal ticket #260.
I will add your comments in there and close this one and try to get this feature prioritized as it is a common request.
