### ISSUE TITLE
Single-Cell Signature Explorer

### ISSUE THREAD

**Issue by FredPont** [HumanCellAtlas/data-portal-content#298]
Thank you for submitting a visualization component package to the HCA DCP Methods Registry!

To expedite your package's addition to https://prod.data.humancellatlas.org/analyze/visualization,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your package's detail page ([example](https://prod.data.humancellatlas.org/analyze/visualization/anatomogram)).

[Required](https://prod.data.humancellatlas.org/contribute/analysis-tools-registry#package-submission-field-details):
- Tool title: Single-Cell Signature Explorer
- Contact name: Frédéric PONT
- Contact email: frederic.pont@inserm.fr
- Who to attribute: Frédéric PONT
- Code repository URL: https://sites.google.com/site/fredsoftwares/products/single-cell-signature-explorer
- Affirm code is free and open source with license available in code repository: [x] (fill in as [x] to affirm)
- Short description: Single-Cell Signature Explorer is a package of softwares dedicated to high throughput signature exploration in single-cell RNAseq analysis.

[Optional](https://prod.data.humancellatlas.org/contribute/analysis-tools-registry#optional-fields-for-methods-and-visualizations):
- Long description: Single-Cell Signature Explorer is a package of four softwares dedicated to high throughput signature exploration in single-cell RNAseq analysis. It is a tool for qualitative and high-throughput scoring of any gene set-based signature at the single cell level and its visualization using t-SNE or UMAP. By scanning datasets for single or combined signatures, it rapidly maps any multi-gene feature.
![screenshot](https://user-images.githubusercontent.com/53525948/62217270-a248c100-b3aa-11e9-8e88-8e92c1d776a1.png)

Reference : Frédéric Pont, Marie Tosolini, Jean J Fournié, Single-Cell Signature Explorer for comprehensive visualization of single cell signatures across scRNA-seq datasets, Nucleic Acids Research, , gkz601, https://doi.org/10.1093/nar/gkz601

**Comment by matthewspeir** [comment]
Thank you, @FredPont, for submitting your tool to the HCA DCP tools registry. We will review the information you have provided and let you know if we have any questions.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/data-portal #490](https://github.com/HumanCellAtlas/data-portal/issues/490) via [**ZenHub**](https://www.zenhub.com/)
