### ISSUE TITLE
Update Analysis Tools sections to use H2 for subsequent (non title) outlines.

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#299]
The "Contact" links and any other non title links can come down from a H1 to a H2 to bring them in line with the reset of the content.

**Comment by frano-m** [comment]
@MillenniumFalconMechanic @NoopDog this was completed as part of #456.

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/49fbd723-dada-4d3a-96bb-0e026ea92d10)

**Comment by NoopDog** [comment]
Super. Thanks @frano-m
