### ISSUE TITLE
Add https://humancellatlas.usegalaxy.eu portal

### ISSUE THREAD

**Issue by pcm32** [HumanCellAtlas/data-portal-content#305]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: Human Cell Atlas Galaxy Instance
- Contact name: Pablo Moreno
- Contact email: pmoreno@ebi.ac.uk
- Who to attribute: P Moreno, N Huang, J Manning, S Mohammed, C Talavera-Lopez, K Polanski, W Bacon, B Gruening, H Rasche, K Meyer, S Teichmann, A Brazma, I Papatheodorou
- Portal URL: https://humancellatlas.usegalaxy.eu
- Short description: The Human Cell Atlas Galaxy instance contains tools for Single Cell analysis and interactive visualisation (UCSC CellBrowser). It can import matrix data from the Human Cell Atlas and the EBI Single Cell Expression Atlas, for re-analysis.

Optional:
- Long description: The Human Cell Atlas Galaxy instance contains tools for Single Cell Clustering (Scanpy, Seurat, Scater/SC3), Trajectories analysis (Scanpy, Monocle) and interactive visualisation (UCSC CellBrowser), allowing simple data analysis through the proven Galaxy user interface. It also includes facilities to import matrix data from the Human Cell Atlas and the EBI Single Cell Expression Atlas, for re-analysis. The clustering workflow for the release 6 of EBI Single Cell Expression Atlas are reproducible through this portal. The portal runs as part of the larger usegalaxy.eu infrastructure and has access to thousands of cores and terabytes of RAM and storage, kindly hosted by the U. of Freiburg, den.bi and Elixir.
- Logo or screenshot: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/blob/develop/img/cell-browser.png

**Comment by matthewspeir** [comment]
Hi, @pcm32. Thank you for submitting an analysis portal. We'll review that it meets our standards at https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards and get back to you soon.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/data-portal #491](https://github.com/HumanCellAtlas/data-portal/issues/491) via [**ZenHub**](https://www.zenhub.com/)
