### ISSUE TITLE
Tweak CLI download instructions to reflect file store and layout changes

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-portal-content#306]
Tweak https://data.humancellatlas.org/guides/quick-start-guide#using-the-cli-to-download-files-listed-in-the-manifest to reflect @jessebrennan's recent download changes.

For example, consider mentioning the `--layout` option and explaining the file store a little bit.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/data-portal #492](https://github.com/HumanCellAtlas/data-portal/issues/492) via [**ZenHub**](https://www.zenhub.com/)
