### ISSUE TITLE
FASTGenomics

### ISSUE THREAD

**Issue by mvonpapen** [HumanCellAtlas/data-portal-content#315]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: FASTGenomics
- Contact name: Michael von Papen
- Contact email: michael.papen@comma-soft.com
- Who to attribute: CC LifeScience @ Comma Soft AG
- Portal URL: www.fastgenomics.org
- Short description: FASTGenomics is a platform to share scRNA-seq data and analyses. Users can either choose from best practices or create individual workflows for the exploration of gene expression data.

Optional:
- Long description: 

**FASTGenomics - a platform to share single-cell RNA sequencing data and analyses using reproducible workflows**

![image](https://user-images.githubusercontent.com/26275671/65528439-ad285980-def4-11e9-9a9a-30f33ff85301.png)

Recent technological advances enable genomics of individual cells, the building blocks of all living organisms. Single cell data characteristics differ from those of bulk data, which led to a plethora of new analytical strategies. However, solutions are only useful for experts and currently, there are no widely accepted gold standards for single cell data analysis. To meet the requirements of analytical flexibility, reproducibility, ease of use and data security, we developed [FASTGenomics](https://www.fastgenomics.org) as a powerful, efficient, versatile, robust, safe and intuitive analytical ecosystem for single-cell transcriptomics [[Scholz et al., 2018](https://doi.org/10.1101/272476)]. This development has been carried out at [Comma Soft](https://www.comma-soft.com), Bonn, in collaboration with the [Schultze lab](https://www.limes-institut-bonn.de/en/research/research-departments/unit-2/schultze-lab/schultze-lab-home/) at LIMES Institute in Bonn, Germany. 

![image](https://user-images.githubusercontent.com/26275671/65528467-b9acb200-def4-11e9-9fd2-e55d02f5f03c.png)

FASTGenomics is designed as a platform for single cell RNA-seq data open to the scientific community. A major feature is to provide highest reproducibility and transparency for single cell data analysis to the whole community. The platform provides publicly available datasets and analyses for exploration and visualization of gene expression data. Using docker containers provides full reproducibility and helps avoiding "works only on my machine" problems. Register now at [https://www.fastgenomics.org](https://www.fastgenomics.org) and have a look at our collection of data sets and example analyses.

FASTGenomics serves as a platform, where you can share your data with the community and test novel algorithms on public data sets with known results. FASTGenomics scales already routinely to more than 300k cells per project and prototype apps suggest that scaling to 1M cells is also possible [[Scholz et al., 2018](https://doi.org/10.1101/272476)]. Moreover, its hybrid design also allows custom solutions such as FASTGenomics on premise for clinical and pharmaceutical research facilities.

For more information, you can find us on [Twitter](https://twitter.com/FastGenomics), [LinkedIn](https://www.linkedin.com/showcase/fastgenomics) or come talk to us on [Slack](https://join.slack.com/t/fastgenomics/signup). To register for the platform visit us at [www.fastgenomics.org](https://www.fastgenomics.org).

**Note**: We will soon offer interactive analyses based on Jupyter notebooks. Stay tuned for the upcoming beta-test!

REFERENCES  
Scholz et al. (2018) [FASTGenomics: An analytical ecosystem for single-cell RNA sequencing data](https://doi.org/10.1101/272476). BioRxiv, 272476.

- Logo or screenshot: ![FG_Logo_Schriftmarke_CMYK](https://user-images.githubusercontent.com/26275671/65526846-0642be00-def2-11e9-8ae6-95af718c0b52.png)

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/data-portal/540.

**Comment by mvonpapen** [comment]
Hi @theathorn ,
I'm not sure if I understand the move to data-portal correctly. FASTGenomics is foremost an analytics platform and not a data portal. Upload and sharing of data is of course part of it, but our focus is on providing a reproducible analysis to our users.

**Comment by matthewspeir** [comment]
Hi @mvonpapen, I believe the 'data-portal-content' repo where the ticket was originally opened is being retired. The contents of that repository and all tickets were moved to the data-portal repo. It's not related to what you submitted. 

 I'll make a ticket to have the links to the templates open up to this repo rather than the data-portal-content repo.

**Comment by theathorn** [comment]
The templates ticket is https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/data-portal/548.

Closing this ticket in favor of https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/data-portal/540.

**Comment by theathorn** [comment]
@NoopDog Please close this ticket - I don't have permissions.
