### ISSUE TITLE
About: What is the Platform: Ingest Service

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#33]
Basic content for section complete

**Comment by kozbo** [comment]
Fill in text for this page
https://dev.data.humancellatlas.org/about/what-is-the-platform/ingest-service

model level of content on this page
https://dev.data.humancellatlas.org/about/what-is-the-platform/secondary-analysis

**Comment by kozbo** [comment]
We see content here that seems sufficient, closing
