### ISSUE TITLE
Learn: Metadata Standard

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#38]
- [x] Implement Learn / Metadata Standards pages (@NoopDog )
- [x] Change the top level title from "Metadata Schema" to "Metadata Standard" (@NoopDog )
- [x] Review pages (Mallory)
- [x] Update documents in metadata-schema repo as needed (Mallory)

**Comment by malloryfreeberg** [comment]
In the metadata-schema repo, we have a handful of markdown documents that describe various aspects of the metadata standard:

- [Overview of Metadata Structure](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/structure.md)
- [Metadata Design and Implementation Choices](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/rationale.md)
- [Metadata Evolution and Update Principles](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/evolution.md)

We also have a few additional docs that are more about updating the standard (contributing changes, release process) that might be outside the scope of an overview of the standard.

@theathorn @NoopDog  As with the Metadata Dictionary ticket, is there a mechanism by which the Data Portal can hook into our existing documents to display them? I would like to avoid duplication, if possible.

**Comment by malloryfreeberg** [comment]
I will discuss with @NoopDog and @willrockout about what the outline should be.

**Comment by malloryfreeberg** [comment]
Proposed structure for the Standards page (which I think is at [about/overview/standards](https://dev.data.humancellatlas.org/about/overview/standards/)?) which will include a section on Metadata standards:

- Data standards
- Metadata standards (this landing page will have some minor content)
    - Metadata Structure [(doc here)](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/structure.md)
    - Metadata Design and Implementation [(doc here)](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/rationale.md)
    - Contributing to Metadata Standard [(doc here)](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/contributing.md)
- Analysis standards?
- Other standards?

@gabsie + @willrockout, what do you think?

**Comment by NoopDog** [comment]
HI @malloryfreeberg, after the rework of the about page the overview section has no left nav or place to list "standards".

How do you feel about adding these text pages as new pages in the left nav here?
https://dev.data.humancellatlas.org/learn/metadata-dictionary/metadata-dictionary

Also

1. Would it be possible add a package.json to the to level of the repo? No worries if its to much of a pain to keep the versions straight. Its just a bit easier to use as input to a node js process. (i can import it with npm) No worries if this cant be done but wanted to check.

1. in the json_schema directory is one of the files there the "entry point" or all all files stand alone and pull in any required schemas?

**Comment by malloryfreeberg** [comment]
@NoopDog Looks great! Under Learn, can you change the top level title from "Metadata Schema" to "Metadata Standard"? The title that is in the same line as "Overview" and "User Guides".

**Comment by malloryfreeberg** [comment]
I updated the ticket to reflect the subtasks that still need to be completed.

**Comment by malloryfreeberg** [comment]
This month (September) the metadata team will be doing a review of our repo docs in preparation for the closed beta. These updates should be reflected in the Portal.

**Comment by theathorn** [comment]
@malloryfreeberg Has the review completed and can this ticket be closed? We should open new tickets fur further refinements.

**Comment by malloryfreeberg** [comment]
Yes, this ticket it done. I am closing it.
