### ISSUE TITLE
Contribute Tab Overview section

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#43]
# Why
As a user I would like to contribute data to the DCP

# Definition of Done
 - The Contribute Tab has an Overview section with the following links:

- [x] "Contact us" - current sends email to data-help@humancellatlas.org
- [x] "See and share"
- [ ] "Prepare metadata"
- [ ] "Upload data"
- [ ] "Detailed instructions"

These links needs to be implemented after reconciling with the Learn / Userguides / Contributing Data section.

**Comment by kbergin** [comment]
I'm not sure if this is the right place, but I noticed that on the current dev contribute page it says this 
![image](https://user-images.githubusercontent.com/9449764/42646475-00f7d160-85cf-11e8-9cd0-b7db5ceb0153.png)

And the part where it says `smartSeq or 10x technology` should say `SmartSeq2 single cell RNA-seq or 10x V2 single cell RNA-seq`

Honestly am unsure about the capitalization of the technology names though @jodihir probably knows.

**Comment by jodihir** [comment]
@theathorn Can you point me to the right doc to update the wording as Kylee mentioned?  The stub doc in the repo doesn't contain it. Maybe it's in another branch?

**Comment by theathorn** [comment]
I think the page is contributeOverviewTemplate.js in the contribute branch of the data-portal repo.
@frano-m or @NoopDog can help.

**Comment by jodihir** [comment]
OK thanks. Maybe the text in the gray box on this page could be moved to the data-portal-content repo page, as it will likely need to be updated fairly often?

**Comment by NoopDog** [comment]
I have created #61  to address the technology names issue raised above.

**Comment by NoopDog** [comment]
Hi @gabsie 

I can point the contact link to the new contact page. Where should these other links go?

"Prepare metadata"
"Upload data"
"See and share"

**Comment by NoopDog** [comment]
* "Contact us" now inks to the contact page
* "See and Share" now links to the data browser

We still need pages/links for:

* "Prepare metadata"
* "Upload data"
* "Detailed Instructions"

Thanks!

**Comment by malloryfreeberg** [comment]
The Contribute Overview landing page should also include some motivation as to why anyone would want to contribute (including what are the benefits)

Tagging myself and @gabsie in this ticket.

**Comment by malloryfreeberg** [comment]
We have updated some copy but will require 2 new sub-pages
1. contribute/overview (current)
1. contribute/how-to-contribute (new)
1. contribute/terms-and-conditions (new)

**Comment by kozbo** [comment]
@NoopDog

**Comment by malloryfreeberg** [comment]
This is done except the T&C, which is now issue #109
