### ISSUE TITLE
Learn Overview: Overview

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#47]

**Comment by theathorn** [comment]
Current paragraph titles include:
    - Learn how to use the Data Portal
    - About data use

**Comment by kozbo** [comment]
This page seems redundant. It just provides links to the same sections that are linked from the left hand panel. Why not remove it?

**Comment by kozbo** [comment]
Change to "Summary"
Expand on content

**Comment by jodihir** [comment]
@malloryfreeberg Please review, especially in terms of whether the paragraph on metadata sounds useful or could be improved.

**Comment by kozbo** [comment]
@malloryfreeberg Please review

**Comment by malloryfreeberg** [comment]
I don't actually see where there is a PR for this issue, so I'm going to leave my review here. Happy to make the PR is someone isn't already working on it, though. Please let me know.

1. 
    
    >This Learn section also contains extensive information about _our_ Metadata _Schema_, including _the_ dictionary, an overview of the metadata structure, and a discussion of design and implementation choices.
    
    Would replace with:
    
    >This Learn section also contains extensive information about **_the_** Metadata **_Standard_**, including **_a_** dictionary _**of metadata fields**_, an overview of the metadata structure, and a discussion of design and implementation choices.
    
1. 
    
    >Please email us at data-help@humancellatlas.org if you have questions!
    
    The email address doesn't appear to be a link in the text. It should be a `mailto:` link. Also, I would replace the exclamation point with a full stop.

1. What is the purpose of the Data Lifecycle and Data Use Agreement sections at the bottom of this page? If none, they should be removed.

**Comment by jodihir** [comment]
Thanks for reviewing this @malloryfreeberg!  I'll make these changes.

**Comment by jodihir** [comment]
@NoopDog Can you remove the Data Lifecycle and Data Use Agreement sections at the bottom of this page?

**Comment by NoopDog** [comment]
@jodihir the teaser docs have been removed from the Learn/Overview. Let me know if this looks ok.

https://dev.data.humancellatlas.org/learn/overview/overview

Cheers,
D

**Comment by jodihir** [comment]
Looks good to me. Maybe I'll add a teaser sentence at the end of the Overview that points people to those links we removed.
