### ISSUE TITLE
Learn Overview: Data Use Agreement

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#49]

**Comment by theathorn** [comment]
Is the https://creativecommons.org/licenses/by/4.0/ the correct license?
If so, we can close this issue.

**Comment by jodihir** [comment]
This is the correct license currently; we don't have any other statement to include at this point.  But we should probably leave this ticket open for now until we're sure there won't be anything else to add.

**Comment by NoopDog** [comment]
Ok moving this back to review column as it seems we are not sure its done.
