### ISSUE TITLE
Learn: User Guides: How to go from Query to Annotated Clusters

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#54]
# Why
As a user I would like to know how to go from Query to Annotated Clusters

# Definition of Done
 - Implement page

**Comment by theathorn** [comment]
Out of scope for Pilot phase.

**Comment by NoopDog** [comment]
Remove from site for now.

**Comment by kozbo** [comment]
Do not remove!
Change to "Quick Start Guide" and move to top of the list on the left hand navigation menu.

**Comment by NoopDog** [comment]
Just rename the existing one.
