### ISSUE TITLE
Learn: User Guides: Accessing Data: FAQ

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#55]
# Why
As a user I would like to read a FAQ on how to use the web site

# Definition of Done
 - Implement page

**Comment by malloryfreeberg** [comment]
Do we know what questions we want in the FAQ? We have a few themes that have come out of ZenDesk, but I'm not sure what the scope of this FAQ should be.

**Comment by kozbo** [comment]
We should start with the ZenDesk items

**Comment by kozbo** [comment]
@NoopDog  Please remove this page
