### ISSUE TITLE
Learn: User Guides: Secondary Analysis: File Formats

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#57]

**Comment by jodihir** [comment]
Some content started; will determine the rest with help from Marcus and Tim in August

**Comment by jodihir** [comment]
@mckinsel Tim said that you have information about the file formats now. Here is the empty stub doc and you can just put the information there. Feel free to add it in any way you have time (eg: a rough bulleted list)- I can edit/write it up after and you can do a review of that. Whatever works.. Thanks!

**Comment by theathorn** [comment]
First draft in final review by @TimothyTickle
