### ISSUE TITLE
Remove Redundant Secondary Analysis Landing Page

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/data-portal-content#59]
I don’t think we need the Overview of Secondary Analysis page (https://dev.data.humancellatlas.org/learn/userguides/secondary-analysis/); it’s not on the site map as far as I can tell. It seems redundant with the What is the Secondary Analysis Service? page and the Secondary Analysis page of the About section.  I need to update the figure anyway, so I think I’ll move that figure and figure legend to the “What is the Secondary Analysis Service ? page. Ultimately,   can you remove the Overview page?

**Comment by NoopDog** [comment]
Hi @jodihir this is ready to review.

**Comment by jodihir** [comment]
OK, I think it's good, thanks.
