### ISSUE TITLE
Ingest Data Brokers Development Guide

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#69]
# Why
As a user I would like to develop an ingest data broker

# Definition of Done
 - Implement "Develop[aka Build]/Development Guides/Ingest Broker Development Guide" page.

**Comment by theathorn** [comment]
@rdgoite what is ETA for this? The current page just has a short intro.

**Comment by tburdett** [comment]
Thanks for the ping @theathorn. Have you got a timeframe in mind for this? Is it OK if we put this into our next sprint (starting Tuesday 2nd)?

**Comment by theathorn** [comment]
@tburdett That sounds fine. We're targeting to have something ready by the end of October for the Closed Beta.
