### ISSUE TITLE
Create left hand menu item "Learn/User Guides/Tertiary Analysis"

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-portal-content#79]
We need a stub doc and left hand nav entry for Learn/User Guides/Tertiary Analysis.

**Comment by NoopDog** [comment]
The page is here:
https://dev.data.humancellatlas.org/learn/userguides/tertiary-analysis

The stub for the top level page in this section is here:
https://github.com/HumanCellAtlas/data-portal-content/tree/master/content/learn/userguides/tertiary-analysis

@jodihi the stub for learn/userguides/tertiary-analysis is created. Who is it again that needs to add the content?

Also are there any sub docs required for this section. Let us know and we can create those as well.

Thanks,
D

**Comment by jodihir** [comment]
@TimothyTickle needs to add content there, and I'll check if additional pages are needed.
