### ISSUE TITLE
Complete Optimus user documentation

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/data-portal-content#83]
Per @jodihir 's suggestions, there are some missing links and metric descriptions. 
See https://github.com/HumanCellAtlas/data-portal-content/pull/78#pullrequestreview-144537650

# Definition of Done (this section has been updated; done is now 3/31/19)
 - [ ] Each link points to the right page
 - [ ] Quick Start Table is accurate and complete
 - [ ] All WDL tasks have links to the WDL, links to the underlying library being executed. 
 - [ ] Information is up to date
 - [ ] Graphic describing the pipeline is accurate
 - [ ] QC metrics page is accurate about metrics about this pipeline 

Older document is here: https://github.com/HumanCellAtlas/data-portal-content/blob/master/content/learn/userguides/data-processing-pipelines/optimus-prime-workflow.md

Plan, as of 2-21-19:
1. Jodi will talk with Kishori and Nick to assemble the information to use to update the documentation.
2. Jodi will update the older document with this information 
3. Kylee and Tim will review the new content and make suggestions for the final draft
4. Jodi will assemble the final draft.
5. Nick and Kishori will review the final draft

**Comment by ambrosejcarr** [comment]
@kbergin for better or worse, I now have no idea how to add something to a sprint or even flag to you that I've made an issue without directly tagging you.

**Comment by jodihir** [comment]
Quick Start Table is also missing some information. Please fill in when available.

**Comment by theathorn** [comment]
@TimothyTickle will review.

**Comment by jodihir** [comment]
We are at a point where final updates can be made to this doc in time for the closed beta.  These updates are in progress.

**Comment by jodihir** [comment]
@NoopDog This document is updated.  Can you make it live again on the portal (we had taken it down)?

**Comment by NoopDog** [comment]
Yup, will do. Thx.

**Comment by jodihir** [comment]
This is done, with the exception of the diagram which is in revision by Janeece.  The new diagram is based on the current graphic on the page.

**Comment by jodihir** [comment]
Graphic currently on the page can be replaced by the new graphic when it is ready. Closing ticket.
