### ISSUE TITLE
Contribute: Overview: links at bottom of page are not functional

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#86]
The "Read more" links under "Prepare metadata" and "Upload data" just refer back to the current overview page.

"Browse data" under "See and share" gets a "Your connection is not private" message linking to https://explore.dev.data.humancellatlas.org/.
In this instance it should be https://dev.explore.data.humancellatlas.org/ and similarly for the integration and staging environments.

**Comment by NoopDog** [comment]
@Dave Rogers the “Prepare metadata” one can point to https://dev.data.humancellatlas.org/contribute/overview/what-to-prepare for now


mallory.freeberg [2 days ago]
The “Upload data” one can point to an SOP we have in GitHub in the dcp-cli repo. The SOP doc isn’t merged up to master, I just put in a PR to do this. When it’s merged, it will be at https://github.com/HumanCellAtlas/dcp-cli/docs/Pilot_submitters_SOP.md

@frano-m lets take a look at this one.
