### ISSUE TITLE
Develop: Development Guides: Tertiary Portal Development Guide

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#87]
Needs implementation.

**Comment by TimothyTickle** [comment]
Reviewed by the Red Box community. This is a draft and has some TBD links.

https://github.com/HumanCellAtlas/data-portal-content/pull/99

**Comment by NoopDog** [comment]
Tim the draft is merged. Looks like some links need to be updated. Thx.

**Comment by vickylihorst** [comment]
@TimothyTickle what's the status on the links mentioned in the previous comment? Should we close this ticket?

**Comment by jodihir** [comment]
@vickylihorst Can you let me know the status of this ticket (or close it if it's ready)?  Thanks!

**Comment by vickylihorst** [comment]
the PR has been merged. @TimothyTickle can we close it?

**Comment by jodihir** [comment]
Completed; closing this.  The Coming Soon links have been made into separate tickets.
