### ISSUE TITLE
Analyze: Portals: About Visualization Portals: contains broken link

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-content#89]
The "Start analyzing Human Cell Atlas" link returns a page not found error.

**Comment by malloryfreeberg** [comment]
**Start analyzing Human Cell Atlas** today! Simply click the "View" button beside a portal summary to navigate. You can also seamlessly load your dataset of interest by clicking the "Use with HCA Data" link for enabled portals.

**Comment by TimothyTickle** [comment]
The link should be targeting https://dev.data.humancellatlas.org/analyze/portals/visualization-portals .

**Comment by TimothyTickle** [comment]
Updated in PR https://github.com/HumanCellAtlas/data-portal-content/pull/102

**Comment by NoopDog** [comment]
Ok thanks this is fixed. Closing
