### ISSUE TITLE
Write a blurb about Pipeline Development Guides

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#95]
https://dev.data.humancellatlas.org/develop/development-guides/development-guides-overview

**Comment by NoopDog** [comment]
@jodihir I have shortened the blurbs to fit in the space and updated them here:
https://dev.data.humancellatlas.org/develop/development-guides/development-guides-overview

**Comment by jodihir** [comment]
That's close - I just need to tweak it a little to the following:
Pipeline Development Guides:
Resources and best practices, including using our portability service to test your pipeline and execution environment.

Tertiary Portal Development Guides:
Technical resources to support your development and integration of analysis applications

**Comment by jodihir** [comment]
OK all set - thanks for letting me know how this is done (I didn't realize they're subtitles).
