### ISSUE TITLE
Write a short blurb about Tertiary Portal Development guides for the Develop section

### ISSUE THREAD

**Issue by jodihir** [HumanCellAtlas/data-portal-content#96]
# Definition of Done
A sentence or two that introduces users to the Tertiary Portal Development Guides, for this overview page:
https://dev.data.humancellatlas.org/develop/development-guides/development-guides-overview

**Comment by vickylihorst** [comment]
@jodihir how does this ticket differ from #87?

**Comment by jodihir** [comment]
@vickylihorst ticket #87 is for a guide meant to contain detailed instructions for portal builders; it will be on this page: https://dev.data.humancellatlas.org/develop/development-guides/tertiary-portal-development-guide

The short blurb (ticket 96) goes on the proceeding page and is just meant to give users a quick overview of the content produced for ticket 96. It should just be 1-3 sentences.  (I'm going to write one for the pipelines so I'll show you what i mean.)

**Comment by jodihir** [comment]
Content for this is here: https://github.com/HumanCellAtlas/data-portal-content/blob/master/content/develop/development-guides/development-guides-overview.md

**Comment by vickylihorst** [comment]
closing per @jodihir as we are all set.
